//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNPXcore.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNPXcore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bitmap Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnCopyBitmap {
            get {
                return ResourceManager.GetString("btnCopyBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnCreateProblemMlt {
            get {
                return ResourceManager.GetString("btnCreateProblemMlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnDefaultSettings {
            get {
                return ResourceManager.GetString("btnDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomePage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnHomePage {
            get {
                return ResourceManager.GetString("btnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnInitialState {
            get {
                return ResourceManager.GetString("btnInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnMethodCheck {
            get {
                return ResourceManager.GetString("btnMethodCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnMethodClear {
            get {
                return ResourceManager.GetString("btnMethodClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnMultiSolve {
            get {
                return ResourceManager.GetString("btnMultiSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standardization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnNomalize {
            get {
                return ResourceManager.GetString("btnNomalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnNumChange {
            get {
                return ResourceManager.GetString("btnNumChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnNumChangeFix {
            get {
                return ResourceManager.GetString("btnNumChangeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Puzzle File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnOpenPuzzleFile {
            get {
                return ResourceManager.GetString("btnOpenPuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnPatternAutoGen {
            get {
                return ResourceManager.GetString("btnPatternAutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnPatternCapture {
            get {
                return ResourceManager.GetString("btnPatternCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnPatternClear {
            get {
                return ResourceManager.GetString("btnPatternClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnProbNxt {
            get {
                return ResourceManager.GetString("btnProbNxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnProbPre {
            get {
                return ResourceManager.GetString("btnProbPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSaveBitmap {
            get {
                return ResourceManager.GetString("btnSaveBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSavePuzzle {
            get {
                return ResourceManager.GetString("btnSavePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSaveToFavorites {
            get {
                return ResourceManager.GetString("btnSaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSolve {
            get {
                return ResourceManager.GetString("btnSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSolveUp {
            get {
                return ResourceManager.GetString("btnSolveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnTransEst {
            get {
                return ResourceManager.GetString("btnTransEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnTransLRg {
            get {
                return ResourceManager.GetString("btnTransLRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   to Beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnTransRes {
            get {
                return ResourceManager.GetString("btnTransRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clockwise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnTransRtg {
            get {
                return ResourceManager.GetString("btnTransRtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnTransUDg {
            get {
                return ResourceManager.GetString("btnTransUDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnUndo {
            get {
                return ResourceManager.GetString("btnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Algorithm List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbAddAlgorithmList {
            get {
                return ResourceManager.GetString("chbAddAlgorithmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional Save if file exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbAdditionalSave {
            get {
                return ResourceManager.GetString("chbAdditionalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Basic Pattern on Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbChangeBasicPattenOnSuccess {
            get {
                return ResourceManager.GetString("chbChangeBasicPattenOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm multiple cells に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbConfirmMultipleCells {
            get {
                return ResourceManager.GetString("chbConfirmMultipleCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Output on Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbFileOutputOnSuccess {
            get {
                return ResourceManager.GetString("chbFileOutputOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format : Line type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbFormatLine {
            get {
                return ResourceManager.GetString("chbFormatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Initial State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbInitialState {
            get {
                return ResourceManager.GetString("chbInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   show Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbNrmlNum {
            get {
                return ResourceManager.GetString("chbNrmlNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Randomizing Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbRandomizingNumbers {
            get {
                return ResourceManager.GetString("chbRandomizingNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save with Answer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSaveWithAnswer {
            get {
                return ResourceManager.GetString("chbSaveWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSetAnswer {
            get {
                return ResourceManager.GetString("chbSetAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSetDifficulty {
            get {
                return ResourceManager.GetString("chbSetDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Candidate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbShowCandidate {
            get {
                return ResourceManager.GetString("chbShowCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show noused digits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbShowNoUsedDigits {
            get {
                return ResourceManager.GetString("chbShowNoUsedDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbShowSolution {
            get {
                return ResourceManager.GetString("chbShowSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Difficulty Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSortByDiffOrder {
            get {
                return ResourceManager.GetString("chbSortByDiffOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbWhiteBack {
            get {
                return ResourceManager.GetString("chbWhiteBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string filePuzzleFile {
            get {
                return ResourceManager.GetString("filePuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SuDoKu Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fldSuDoKuImages {
            get {
                return ResourceManager.GetString("fldSuDoKuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string gbxMSearchCondition {
            get {
                return ResourceManager.GetString("gbxMSearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Omit multiple candidates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenLS_turbo {
            get {
                return ResourceManager.GetString("GenLS_turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAlgorithmM {
            get {
                return ResourceManager.GetString("lblAlgorithmM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Search Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAllSearchOption {
            get {
                return ResourceManager.GetString("lblAllSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblALSSizeMax {
            get {
                return ResourceManager.GetString("lblALSSizeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAnalysisLevel {
            get {
                return ResourceManager.GetString("lblAnalysisLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAppliedCount {
            get {
                return ResourceManager.GetString("lblAppliedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Pattern: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblBasicPattern {
            get {
                return ResourceManager.GetString("lblBasicPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblCellsPuzzle {
            get {
                return ResourceManager.GetString("lblCellsPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblCellsSolved {
            get {
                return ResourceManager.GetString("lblCellsSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblChangeNumber {
            get {
                return ResourceManager.GetString("lblChangeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblClickOnNumber {
            get {
                return ResourceManager.GetString("lblClickOnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create / Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblCreateEdit {
            get {
                return ResourceManager.GetString("lblCreateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblDifficulty {
            get {
                return ResourceManager.GetString("lblDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblDifficultyM {
            get {
                return ResourceManager.GetString("lblDifficultyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed Time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblElapsedTime {
            get {
                return ResourceManager.GetString("lblElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblEpapsedTimeTS3 {
            get {
                return ResourceManager.GetString("lblEpapsedTimeTS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblForceChainType {
            get {
                return ResourceManager.GetString("lblForceChainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Rank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblGenLogMaxRank {
            get {
                return ResourceManager.GetString("lblGenLogMaxRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblGenLogMaxSize {
            get {
                return ResourceManager.GetString("lblGenLogMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblGNLType {
            get {
                return ResourceManager.GetString("lblGNLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMaxAlgorithm {
            get {
                return ResourceManager.GetString("lblMaxAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMaxAllAlgorithm {
            get {
                return ResourceManager.GetString("lblMaxAllAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblMaximum {
            get {
                return ResourceManager.GetString("LblMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblMaxLevel {
            get {
                return ResourceManager.GetString("LblMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMaxTime {
            get {
                return ResourceManager.GetString("lblMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblMethod {
            get {
                return ResourceManager.GetString("LblMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method And Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMethodAndOrder {
            get {
                return ResourceManager.GetString("lblMethodAndOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method is set by Solve/Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMethodSetting {
            get {
                return ResourceManager.GetString("lblMethodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMinimum {
            get {
                return ResourceManager.GetString("lblMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNLMaxSize {
            get {
                return ResourceManager.GetString("lblNLMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cells:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfCells {
            get {
                return ResourceManager.GetString("lblNoOfCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzles: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfPuzzles {
            get {
                return ResourceManager.GetString("lblNoOfPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trials: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfTrials {
            get {
                return ResourceManager.GetString("lblNoOfTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfTrialsCanceled {
            get {
                return ResourceManager.GetString("lblNoOfTrialsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cum. Trials: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfTrialsCum {
            get {
                return ResourceManager.GetString("lblNoOfTrialsCum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPattern {
            get {
                return ResourceManager.GetString("lblPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzle {
            get {
                return ResourceManager.GetString("lblPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle Creation Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzleCreationType {
            get {
                return ResourceManager.GetString("lblPuzzleCreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (0: Standard 1: High speed 2:Exhaustive search ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzleCreationType2 {
            get {
                return ResourceManager.GetString("lblPuzzleCreationType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Problem Level: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzleLevel {
            get {
                return ResourceManager.GetString("lblPuzzleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random Seed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblRandomNumberSeed {
            get {
                return ResourceManager.GetString("lblRandomNumberSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveAll {
            get {
                return ResourceManager.GetString("lblSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveCurrentPuzzle {
            get {
                return ResourceManager.GetString("lblSaveCurrentPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (0:Auto 0&gt;:seed Seting) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSeedSetting {
            get {
                return ResourceManager.GetString("lblSeedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblStep {
            get {
                return ResourceManager.GetString("lblStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblStepM {
            get {
                return ResourceManager.GetString("lblStepM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transformation(Asymmetric) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblTransAsymetric {
            get {
                return ResourceManager.GetString("lblTransAsymetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transformation(Symmetric) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblTransSymetric {
            get {
                return ResourceManager.GetString("lblTransSymetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   under Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblUnderAnalysis {
            get {
                return ResourceManager.GetString("lblUnderAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnSolved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lvlCellsUnsolved {
            get {
                return ResourceManager.GetString("lvlCellsUnsolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgAnalysisComplate {
            get {
                return ResourceManager.GetString("msgAnalysisComplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are cells with no candidate digits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNoSolution {
            get {
                return ResourceManager.GetString("msgNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSuspend {
            get {
                return ResourceManager.GetString("msgSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper Limit Break に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUpperLimitBreak {
            get {
                return ResourceManager.GetString("msgUpperLimitBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper Limit Time Break に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUpperLimitTimeBreak {
            get {
                return ResourceManager.GetString("msgUpperLimitTimeBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Symmetry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel00 {
            get {
                return ResourceManager.GetString("patSel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Symmetry (90 degrees) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel01 {
            get {
                return ResourceManager.GetString("patSel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Symmetry (180 degrees) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel02 {
            get {
                return ResourceManager.GetString("patSel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (vertical) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel03 {
            get {
                return ResourceManager.GetString("patSel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (horizontal) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel04 {
            get {
                return ResourceManager.GetString("patSel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (lower right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel05 {
            get {
                return ResourceManager.GetString("patSel05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (upper right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string patSel06 {
            get {
                return ResourceManager.GetString("patSel06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabACreate {
            get {
                return ResourceManager.GetString("tabACreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAFile {
            get {
                return ResourceManager.GetString("tabAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomePage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAHomepage {
            get {
                return ResourceManager.GetString("tabAHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAOption {
            get {
                return ResourceManager.GetString("tabAOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabASolve {
            get {
                return ResourceManager.GetString("tabASolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transform に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabATransform {
            get {
                return ResourceManager.GetString("tabATransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAuto {
            get {
                return ResourceManager.GetString("tabAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMethod {
            get {
                return ResourceManager.GetString("tabBMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMethodOption {
            get {
                return ResourceManager.GetString("tabBMethodOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MultiSolve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMultiSolve {
            get {
                return ResourceManager.GetString("tabBMultiSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBSolve {
            get {
                return ResourceManager.GetString("tabBSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabManual {
            get {
                return ResourceManager.GetString("tabManual", resourceCulture);
            }
        }
    }
}
