//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNPZ_sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNPZ_sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Open Puzzle File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnOpenPuzzleFile {
            get {
                return ResourceManager.GetString("btnOpenPuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnProbNxt {
            get {
                return ResourceManager.GetString("btnProbNxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnProbPre {
            get {
                return ResourceManager.GetString("btnProbPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSavePuzzle {
            get {
                return ResourceManager.GetString("btnSavePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnSaveToFavorites {
            get {
                return ResourceManager.GetString("btnSaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Algorithm List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbAddAlgorithmList {
            get {
                return ResourceManager.GetString("chbAddAlgorithmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional Save if file exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbAdditionalSave {
            get {
                return ResourceManager.GetString("chbAdditionalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format : Line type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbFormatLine {
            get {
                return ResourceManager.GetString("chbFormatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Initial State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbInitialState {
            get {
                return ResourceManager.GetString("chbInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save with Answer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSaveWithAnswer {
            get {
                return ResourceManager.GetString("chbSaveWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Difficulty Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSortByDiffOrder {
            get {
                return ResourceManager.GetString("chbSortByDiffOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblDifficulty {
            get {
                return ResourceManager.GetString("lblDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzle {
            get {
                return ResourceManager.GetString("lblPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveAll {
            get {
                return ResourceManager.GetString("lblSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveCurrentPuzzle {
            get {
                return ResourceManager.GetString("lblSaveCurrentPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MultiSolve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tab2MultiSolve {
            get {
                return ResourceManager.GetString("tab2MultiSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tab2Solve {
            get {
                return ResourceManager.GetString("tab2Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabConversion {
            get {
                return ResourceManager.GetString("tabConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabACreate {
            get {
                return ResourceManager.GetString("tabACreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabFile {
            get {
                return ResourceManager.GetString("tabFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomePage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabHomepage {
            get {
                return ResourceManager.GetString("tabHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabOption {
            get {
                return ResourceManager.GetString("tabOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabSolve {
            get {
                return ResourceManager.GetString("tabSolve", resourceCulture);
            }
        }
    }
}
